"""Generate CommonMark Unicode punctuation (P/S) ranges from pinned Unicode 16.0.0.

curl -fsSLO https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
python3 scripts/generate-punctuation.py UnicodeData.txt > lua/md-render/unicode_punctuation.lua

Uses the same UnicodeData.txt as generate-casefold.py. Review the source hash
and generated diff when updating; no Python or Unicode download is needed at runtime.
"""

import hashlib
from pathlib import Path
import sys

SHA256 = "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: generate-punctuation.py UnicodeData.txt")
    data = Path(sys.argv[1]).read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        sys.exit("UnicodeData.txt does not match the pinned Unicode 16.0.0 SHA-256")
    ranges = []
    for line in data.decode().splitlines():
        fields = line.split(";")
        if fields[2][0] not in ("P", "S"):
            continue
        cp = int(fields[0], 16)
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    print("-- Generated by scripts/generate-punctuation.py; do not edit by hand.")
    print("-- Unicode 16.0.0 punctuation and symbols (general categories P/S).")
    print("-- https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt")
    print(f"-- SHA-256: {SHA256}")
    print("-- Unicode data license: https://www.unicode.org/license.txt")
    print("-- SPDX-License-Identifier: Unicode-3.0")
    print("-- Copyright © 1991-2024 Unicode, Inc.")
    print("""--
-- Permission is hereby granted, free of charge, to any person obtaining a
-- copy of data files and any associated documentation (the "Data Files") or
-- software and any associated documentation (the "Software") to deal in the
-- Data Files or Software without restriction, including without limitation
-- the rights to use, copy, modify, merge, publish, distribute, and/or sell
-- copies of the Data Files or Software, and to permit persons to whom the
-- Data Files or Software are furnished to do so, provided that either (a)
-- this copyright and permission notice appear with all copies of the Data
-- Files or Software, or (b) this copyright and permission notice appear in
-- associated Documentation.
--
-- THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
-- KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
-- THIRD PARTY RIGHTS.
-- IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
-- BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
-- OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
-- WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
-- ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
-- FILES OR SOFTWARE.
--
-- Except as contained in this notice, the name of a copyright holder shall
-- not be used in advertising or otherwise to promote the sale, use or other
-- dealings in these Data Files or Software without prior written
-- authorization of the copyright holder.""")
    print("\nreturn {")
    for first, last in ranges:
        print(f"  {{ 0x{first:X}, 0x{last:X} }},")
    print("}")
