"""Generate Unicode full-case-fold exceptions to Neovim's simple tolower().

curl -fsSLO https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt
curl -fsSLO https://www.unicode.org/Public/16.0.0/ucd/UnicodeData.txt
python3 scripts/generate-casefold.py CaseFolding.txt UnicodeData.txt > lua/md-render/casefold.lua

To update, pin both files from the same Unicode release and review their hashes
and the generated diff. Runtime lookup needs only Neovim; Python is build-only.
"""

import hashlib
from pathlib import Path
import sys


SOURCES = {
    "CaseFolding.txt": "6f1f9c588eb4a5c718d9e8f93b782685e5c7fec872cf05e8e6878053599e09bb",
    "UnicodeData.txt": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
}


def verified(path, name):
    data = Path(path).read_bytes()
    if hashlib.sha256(data).hexdigest() != SOURCES[name]:
        sys.exit(f"{name} does not match the pinned Unicode 16.0.0 SHA-256")
    return data.decode().splitlines()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: generate-casefold.py CaseFolding.txt UnicodeData.txt")
    folds = {}
    for line in verified(sys.argv[1], "CaseFolding.txt"):
        fields = line.partition("#")[0].split(";")
        if len(fields) > 3 and fields[1].strip() in ("C", "F"):
            folds[int(fields[0], 16)] = tuple(int(cp, 16) for cp in fields[2].split())
    exceptions = {}
    for line in verified(sys.argv[2], "UnicodeData.txt"):
        fields = line.split(";")
        cp = int(fields[0], 16)
        lower = (int(fields[13], 16),) if fields[13] else (cp,)
        folded = folds.get(cp, (cp,))
        if folded != lower:
            exceptions[cp] = folded
    print("-- Generated by scripts/generate-casefold.py; do not edit by hand.")
    print("-- Unicode 16.0.0 full (C/F), non-Turkic case folding: exceptions to simple lowercase.")
    for name, digest in SOURCES.items():
        print(f"-- https://www.unicode.org/Public/16.0.0/ucd/{name}")
        print(f"-- SHA-256: {digest}")
    print("-- Unicode data license: https://www.unicode.org/license.txt")
    print("-- SPDX-License-Identifier: Unicode-3.0")
    print("-- Copyright © 1991-2024 Unicode, Inc.")
    print("""--
-- Permission is hereby granted, free of charge, to any person obtaining a
-- copy of data files and any associated documentation (the "Data Files") or
-- software and any associated documentation (the "Software") to deal in the
-- Data Files or Software without restriction, including without limitation
-- the rights to use, copy, modify, merge, publish, distribute, and/or sell
-- copies of the Data Files or Software, and to permit persons to whom the
-- Data Files or Software are furnished to do so, provided that either (a)
-- this copyright and permission notice appear with all copies of the Data
-- Files or Software, or (b) this copyright and permission notice appear in
-- associated Documentation.
--
-- THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
-- KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
-- THIRD PARTY RIGHTS.
-- IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
-- BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
-- OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
-- WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
-- ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
-- FILES OR SOFTWARE.
--
-- Except as contained in this notice, the name of a copyright holder shall
-- not be used in advertising or otherwise to promote the sale, use or other
-- dealings in these Data Files or Software without prior written
-- authorization of the copyright holder.""")
    print("\nreturn {")
    for cp, folded in sorted(exceptions.items()):
        value = "".join(f"\\u{{{item:X}}}" for item in folded)
        print(f'  ["\\u{{{cp:X}}}"] = "{value}",')
    print("}")
