"""Generate the offline Lua table from a verified WHATWG entities.json download.

curl -fsSL https://html.spec.whatwg.org/entities.json -o /tmp/entities.json
python scripts/generate-html-entities.py /tmp/entities.json > lua/md-render/html_entities.lua
"""

import hashlib
import json
from pathlib import Path
import re
import sys


SOURCE_SHA256 = "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6"
HEADER = """-- Generated by scripts/generate-html-entities.py; do not edit by hand.
-- Source: https://html.spec.whatwg.org/entities.json (verified 2026-09-29)
-- Source SHA-256: d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6
-- All 2,125 semicolon-terminated names; keys omit the surrounding & and ;.
-- WHATWG licenses specification portions incorporated into source under BSD-3-Clause:
-- https://github.com/whatwg/html/blob/main/LICENSE
-- SPDX-License-Identifier: BSD-3-Clause
-- Copyright © WHATWG (Apple, Google, Mozilla, Microsoft).
--
-- Redistribution and use in source and binary forms, with or without
-- modification, are permitted provided that the following conditions are met:
--
-- 1. Redistributions of source code must retain the above copyright notice, this
--    list of conditions and the following disclaimer.
-- 2. Redistributions in binary form must reproduce the above copyright notice,
--    this list of conditions and the following disclaimer in the documentation
--    and/or other materials provided with the distribution.
-- 3. Neither the name of the copyright holder nor the names of its
--    contributors may be used to endorse or promote products derived from
--    this software without specific prior written permission.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-- FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-- DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-- CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

return {
"""


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: generate-html-entities.py /path/to/entities.json")
    source = Path(sys.argv[1]).read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        sys.exit("entities.json does not match the verified source SHA-256")
    entries = json.loads(source)
    lines = [HEADER]
    for name, entry in sorted(entries.items()):
        if not name.endswith(";"):
            continue
        assert re.fullmatch(r"&[A-Za-z][A-Za-z0-9]*;", name), name
        assert entry["characters"] == "".join(map(chr, entry["codepoints"])), name
        value = "".join(f"\\u{{{ord(char):X}}}" for char in entry["characters"])
        lines.append(f'  ["{name[1:-1]}"] = "{value}",\n')
    lines.append("}\n")
    sys.stdout.write("".join(lines))
